# nginx service for nginx app
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

  # portfoward to test
  # kubectl port-forward svc/nginx-service 8081:80