# a job that prints in logs the current date and time 
apiVersion: batch/v1
kind: Job
metadata:
  name: print-date-job
spec:
  template:
    spec:
      containers:
      - name: print-date
        image: busybox
        command: ["date"]
      restartPolicy: Never