apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-interactive
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
    stdin: true
    tty: true
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: ubuntu-pvc
  restartPolicy: Never
