apiVersion: v1
kind: Pod
metadata:
  name: pod-resources-limit
spec:
  containers:
  - name: main-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
